# 端口
server:
  port: 8083

#spring:
#  profiles:
    # 指定配置
    # route_simple：简单尝试
    # route_stripPrefix：截取请求
    # route_uri：转发指定地址并传入参数
    # route_addRequestParameter：转发指定服务并传入参数
    # route_hystrix：熔断
    # route_requestRateLimiter：限流
    # route_all：综合
#    active: route_all

---

spring:
  # 配置文件名称，用来标识不同环境的配置。由 spring.profiles.active 的值来决定使用哪组配置。
  ## 简单尝试
#  profiles: route_all
  application:
    # 应用名称
    name: app-eureka-gateway
  cloud:
    gateway:
      discovery:
        locator:
          # 是否和服务注册与发现组件结合，设置为 true 后可以直接使用应用名称调用服务
          enabled: true
          lower-case-service-id: true #服务id设置为小写
      # 路由（routes：路由，它由唯一标识（ID）、目标服务地址（uri）、一组断言（predicates）和一组过滤器组成（filters）。filters 不是必需参数。）
      routes:
        # 路由标识（id：标识，具有唯一性）   简单尝试
        - id: route_customer
          # 目标服务地址（uri：地址，请求转发后的地址）
          uri: lb://app-eureka-customer
          # 路由条件（predicates：断言，匹配 HTTP 请求内容）
          predicates:
          ## 匹配 GET 请求
#          - Method=GET
          ## 转发地址格式为 uri/archive
          - Path=/customer/**
          filters:
          ## 截取路径位数
          - StripPrefix=1
        # 路由标识（id：标识，具有唯一性）   简单尝试
        - id: route_provider
          # 目标服务地址（uri：地址，请求转发后的地址）
          uri: lb://app-eureka-provider
          # 路由条件（predicates：断言，匹配 HTTP 请求内容）
          predicates:
            ## 匹配 GET 请求
#            - Method=GET
            ## 转发地址格式为 uri/archive
            - Path=/provider/**
          filters:
            ## 截取路径位数
            - StripPrefix=1

logging:
  level:
    # log 级别
    org.springframework.cloud.gateway: debug