server:
  port: 8091
eureka:
  instance:
    hostname: localhost
  server:
    enableSelfPreservation: true
    renewalPercentThreshold: 0.1
  client:
    register-with-eureka: false
    fetch-registry: false
service-url:
  defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #×¢²áÖĞĞÄµØÖ·