server:
  port: 8084

spring:
  application:
    name: app-eureka-security
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/oauth2?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  main:
    allow-bean-defintion-overriding: true #允许覆盖IOC内对象

mybatis:
  configuration:
    #开启驼峰
    map-underscore-to-camel-case: true
    #日志打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 实体类路径
  type-aliases-package: com.eureka.security.domain
  # 映射文件路径
  mapper-locations: mapper/*.xml

#  cloud:
#    stream:
#      kafka:
#        binder:
#          brokers: localhost:9092         #Kafka的消息中间件服务器
#          zk-nodes: localhost:2181        #Zookeeper的节点，如果集群，后面加,号分隔
#          auto-create-topics: true        #如果设置为false,就不会自动创建Topic 有可能你Topic还没创建就直接调用了。
#      bindings:
#        output:      #这里用stream给我们提供的默认output，后面会讲到自定义output
#          destination: stream-demo    #消息发往的目的地
#          content-type: text/plain    #消息发送的格式，接收端不用指定格式，但是发送端要
