server:
  port: 8082
spring:
  application:
    name: app-eureka-customer
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///oauth2
    username: root
    password: root
  main:
    allow-bean-defintion-overriding: true #允许覆盖IOC内对象
mybatis:
  configuration:
    #开启驼峰
    map-underscore-to-camel-case: true
    #日志打印sql
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: mapper/*.xml
  #  check-config-location: true
  type-aliases-package: com.eureka.security.**
#  cloud:
#    stream:
#      kafka:
#        binder:
#          brokers: localhost:9092         #Kafka的消息中间件服务器
#          zk-nodes: localhost:2181        #Zookeeper的节点，如果集群，后面加,号分隔
#          auto-create-topics: true        #如果设置为false,就不会自动创建Topic 有可能你Topic还没创建就直接调用了。
#      bindings:
#        input: #input是接收，注意这里不能再像前面一样写output了
#          destination: stream-demo #消息接收的目的地